### PR TITLE
Add newer version of stats.py & dockerfile!

### PR DESCRIPTION
**Pull request by Macleykun**
This PR is still in draft, as it's not tested on a fresh OS and therefore it's not garantueed this one works withoud maybe enabling something on the host OS first.

This PR adds the stats2.py which fixes the cpu usage as this is incorrectly showing the %, while it technically shows the amount of load as x/4 (not x/100%). Basically it shows the load of the past 1 minute. So on a quad core cpu a load of 4 would mean 100% load, and anything higher would lead to 101% or higher. However it's not the current CPU usage in %.

The stats2.py also revamps some command's and data to fit them properly on the display. The way it's setup it should work withoud overlapping text.

Also the icons that were added in [monitor.py](https://github.com/mklements/OLED_Stats/blob/main/monitor.py) are resized to accompany the original design.

Lastly, this PR will ignore .vscode folder as this is something you don't want to commit to a upstream repo, a system file to run the script using systemd (easy to run/stop and enable/disable on startup!).

Todo:
- [ ] Get feedback on functionality
- [x] Verify if this setup work on a brand new 64-bit OS rpi. I may just opt in to re-read the steps from your site and see if toggeling something back that i don't do in the container brings any problems.
- [ ] Get a upstream image for way easier and faster setup for end-users (and updates aswell!)
- [ ] Write documentation
- [ ] (possibly CI/CD? probably not b/c of overkill, unless we can copy paste smth).

### CODE REVIEW

**Comment by Macleykun** [comment]
As i though! On the host the interface is not exposed out of the box and can be easily enabled by doing:
`sudo raspi-config nonint do_i2c 0`

I don't think futher testing is needed from my side. I'll await your feedback.

**Comment by Macleykun** [comment]
The only thing i notice running this container is that it has a moderate amount of cpu usage compared to other docker containers:
image
During the evening i have a sleep of 60, i'll see if that changes the cpu usage somehwat.

Changing the nice value has no effect, i assume this has to do that we basically refresh every second. I'll monitor this during the night

**Comment by Macleykun** [comment]
one small bug i found, is that before the first day, the command will show the hour minutes on the stats display.
Technically it still tells the time but not what the numbers mean. But after the first day it makes sense again. The w and uptime command both dont'provie anything handy.

**Comment by Macleykun** [comment]
I added a different uptime command that now displays 0 days instead.
I think this is the best methode unless we really specifically wanna say the minutes and after minutes the hours.

uptime -p does have that, but i think it won't be worth the time and effort to find out a clever way to display time as:
1 minute
1 hour
1 day
8 days etc.

**Comment by Macleykun** [comment]
image
cpu usage still is a bit weird. But will monitor how it goes.

**Comment by Macleykun** [comment]
Noticed timezone is UTC and that may throw some users off. Need to mount or specify timezone.

**Comment by Macleykun** [comment]
so, it seems that the traffic between devices and the container is also measured in the network which is interesting :) but explains why there was any network traffic at all.
Will continue to monitor now more properly in the next hour.

**Comment by Macleykun** [comment]
so, monitoring the usage i can't make much head or tails b/c grafana somehow changes the amount of % when i zoom or zoom out on the timeline. Not sure why.

I do believe the script uses way more then other services i have running, but i'm not sure how to minimize the cpu usage of a python script really.

That's all what i have to do/say about the script stuff :) i'll await your reply!

**Comment by Macleykun** [comment]
IMG_2614
would also help if i added the image itself of the stats2.py ofc :)

**Comment by Macleykun** [comment]
Seems that the uptime fix doesn't work sadly, so i gotta find something else for that sadly.

Install steps:

Only do these steps if you don't have docker yet!:
```
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh
```

Setup steps:
```
sudo raspi-config nonint do_i2c 0
git clone https://github.com/Macleykun/OLED_Stats
cd OLED_Stats
docker build -t test .
docker run -d -v /etc/timezone:/etc/timezone -v /etc/localtime:/etc/localtime --network=host --device=/dev/i2c-1 --device=/dev/gpiomem --name test test-stats
```

**Comment by Macleykun** [comment]
fixed the uptime for ya!
now displays x min, the first hour it'll show: x hours, after that only x days!

**Comment by Macleykun** [comment]
This latest commit makes it so, that on linux the execution bit is turned on. 
Aswell as specifying the python3 path, it's as easy as: ./stats.py to run it :)

**Comment by mklements** [comment]
I've created a new docker repository to work on the docker version - https://github.com/mklements/OLED_Stats_Docker
This will mainly help with keeping the instruction sets separate as I find new users are easily confused when there are multiple "configuration" or OS options. 

I've tried the script out on my Pi and got it running without any major issues. I still need to try it on a fresh install and add in any install steps that may be missing. The Pi I ran it on is one that already had my other scripts running in the past so may have libraries already installed.

**Pull request closed without merging**
